### ISSUE TITLE
Question : Is it possible to set canvas as image data (like with dataURi)

### ISSUE THREAD

**Issue by niusha-paks** [open-xml-templating/docxtemplater-image-module#16]
Hello and thank you for this library,

Is it possible to set canvas dataURi as an image data in the following example :

docx=new DocxGen()
    .attachModule(imageModule)
    .load(content)
    .setData({image:'examples/image.png'})
    .render()

With a dataURi based on a canvas : 

var canvas = document.getElementById("myCanvas");
var data = canvas.toDataURL("image/png");

Thank you,

Niusha

**Comment by edi9999** [comment]
Yes you can. I don't have much time to go into detail, but you can have a look at #5

**Comment by niusha-paks** [comment]
Hi, thanks for your response. I will try to do it and post the solution here if it works.

**Comment by niusha-paks** [comment]
Hello, because the app has to be used in IE8, I will not use that functionnality at all.

The canvas I wanted to add in the .docx are charts (constructed with flotchart and excanvas for IE8).

Excanvas does'nt implemented .toDataURL(), so I think I will construct these charts by injecting custom XML in the docx : http://javascript-ninja.fr/docxtemplater/v1/examples/demo.html#rawxml

Have a nice day

Niusha

**Comment by edi9999** [comment]
Yes I think this is the less of a hassle to implement if you need ie8 support.

It will be quite difficult to have the exact same rendering tough

**Comment by niusha-paks** [comment]
Hello,

Finally, I used canvas.toDataURL to put the graphs in the .docx file, as the user will use Chrome in order to use the application.

Firstly, I convert the .toDataURI in an ArrayBuffer with this function (got from http://stackoverflow.com/questions/20691320/save-captured-png-as-arraybuffer) :

```javascript
var base64DataURLToArrayBuffer = exports.base64DataURLToArrayBuffer = function (dataURL) {
           
            string_base64 = dataURL.replace(/^data:image\/(png|jpg);base64,/, "");

            var binary_string = window.atob(string_base64);
            var len = binary_string.length;
            var bytes = new Uint8Array(len);

            for (var i = 0; i < len; i++) {
                var ascii = binary_string.charCodeAt(i);
                bytes[i] = ascii;
            }

            return bytes.buffer;
        };
```

Then, inspired by issue #5, I rewrited ImageModule.getImageFromData() as this :

```javascript
ImageModule.prototype.getImageFromData = function(imgData) {
    /**
    *   Modified in order to handle canvas dataToURI images :
    *   https://github.com/open-xml-templating/docxtemplater-image-module/issues/16
    *   https://github.com/open-xml-templating/docxtemplater-image-module/issues/5
    *   return fs.readFileSync(imgData);
    **/
    return imgData;
  };
```

**Comment by edi9999** [comment]
Ok great to see that it works for you
