### ISSUE TITLE
Image path passed as variables not working

### ISSUE THREAD

**Issue by balasivagnanam** [open-xml-templating/docxtemplater-image-module#18]
I have the images being dynamically created using camera so the url of the images are passed as variables. so I coded something like this but if I use the hardcoded path it works but when I use the variable name and assign it, the image is not rendered in word file.

```
var imageUrl = chairAssesment.heightImageUrl;
    //console.log("image path after conversion",imageUrl);
    imageUrl = "'" + imageUrl + "'";
    console.log("image path after adding quote",imageUrl);
    
    ImageModule=Meteor.npmRequire('docxtemplater-image-module');

            imageModule=new ImageModule({centered:false});

            imageModule.getSizeFromData=function(imgData) {
            console.log('ok');
            sizeOf=Meteor.npmRequire('image-size');
            sizeObj=sizeOf(imgData);
            console.log(sizeObj);
            return [sizeObj.width,sizeObj.height];
            }

            doc.attachModule(imageModule)
                .load(content)
                .setData({
                first_name:name,
                last_name:lastname,
                phone:"0652455478",
                company_name:"Synergo Consulting",
                city_name:"Singapore",
                para_header:"1.Upper and lower back fully supported",
                para_content:"This is some sample content which I am writing here because I dont know what to write here so better not to try to make any sense of this paragraph",
                para_problem : "No Problem",
                para_recommendation : "continue to work in same manner",
                para_recommendation_2 : "it is not good to work in this manner, Take periodic brakes, do wrist exercises",
                    image:'/mytests/ergoassist/ergoassist/public/template/ergologo.png',
                    pointer: '/mytests/ergoassist/ergoassist/public/template/pointer.png',
                    dataimage: imageUrl,
                    ok_image: '/mytests/ergoassist/ergoassist/public/template/problem.png',
                    nok_image: '/mytests/ergoassist/ergoassist/public/template/not_ok.png'
                    });

```

**Comment by edi9999** [comment]
What does imageUrl contain ? 

You probably have to overwrite getImageFromData (see #16)

**Comment by balasivagnanam** [comment]
imageUrl has the path for the image file, jpeg to insert into the document
Set 1 - With dynamic url/path
![image](https://cloud.githubusercontent.com/assets/4233785/8337222/5fa596d6-1adc-11e5-9fe3-ae56707a3f7e.png)
You can see the image missing here (refer next screen for report with static url/path)
![image](https://cloud.githubusercontent.com/assets/4233785/8337228/68d935aa-1adc-11e5-9fa9-af0754e45019.png)

Set 2 - With static url/path
![image](https://cloud.githubusercontent.com/assets/4233785/8337284/df6e35d0-1adc-11e5-8807-032411faa4af.png)

![image](https://cloud.githubusercontent.com/assets/4233785/8337297/f07f6560-1adc-11e5-8fb2-aae6a6464093.png)

**Comment by edi9999** [comment]
You shouldn't be adding a quote to your variable. If the image isn't added it is because it doesn't exist (probably because of the quotes)

**Comment by balasivagnanam** [comment]
ahh.. yes, I made the quotes after some change thinking that the path is not getting picked up without quotes, removing quotes works... thanks a lot

**Comment by edi9999** [comment]
Great
