### ISSUE TITLE
How to set image size directly in pixels?

### ISSUE THREAD

**Issue by acrolink** [open-xml-templating/docxtemplater-image-module#22]
How to specify the width and height as the image should appear inside Word using mere predefined integers (pixels)? Thanks.

**Comment by edi9999** [comment]
What exactly would you like to do ?

The same size for each image ? Then it should be : 

```
imageModule=new ImageModule({centered:false})
imageModule.getSizeFromData=function(imgData) {
   return [100,100];
}
```

The real size of the image ?

```
imageModule=new ImageModule({centered:false})
imageModule.getSizeFromData=function(imgData) {
   sizeOf=require('image-size');
   sizeObj=sizeOf(imgData);
   console.log(sizeObj);
   return [sizeObj.width,sizeObj.height];
}
```

**Comment by acrolink** [comment]
Thanks very much Egdar.
		
		 ---- On Wed, 19 Aug 2015 09:49:30 +0300  notifications@github.com  wrote ----What exactly would you like to do ?
The same size for each image ? Then it should be : 
imageModule=new ImageModule({centered:false})
imageModule.getSizeFromData=function(imgData) {
   return [100,100];
}

The real size of the image ?
imageModule=new ImageModule({centered:false})
imageModule.getSizeFromData=function(imgData) {
   sizeOf=require('image-size');
   sizeObj=sizeOf(imgData);
   console.log(sizeObj);
   return [sizeObj.width,sizeObj.height];
}
