### ISSUE TITLE
Passing tag name to getImage / getSize 

### ISSUE THREAD

**Issue by Takeno** [open-xml-templating/docxtemplater-image-module#25]
Hi,

I propose to add TagName to callbacks getImage and getSize, giving the chance to customize options based on placeholder.

Scenario: two different images with different sizes in particular document template.
```
// doc.docx
{%logo} bla bla bla {%thumbnail}
```

```
// app.js
var opts = {};
opts.centered = false;
opts.getImage = function(tagValue) {
    return fs.readFileSync(tagValue, 'binary');
};
opts.getSize = function(img, tagValue) {
    return [200, 100];
};
var imageModule = new ImageModule(opts);
```
In this way I'll have two images with the same size.
Passing tagName we'll be able to have custom strategy:

```
var opts = {};
opts.centered = false;
opts.getImage = function(tagValue, tagName) {
    // I don't need to change image path
    return fs.readFileSync(tagValue, 'binary');
};
opts.getSize = function(img, tagValue, tagName) {
    // resize strategy
    switch(tagName) {
        case 'logo':
            return [200, 100];
        case 'thumbnail':
            return [75, 75];
        default:
            return [150, 150];
    }
};
var imageModule = new ImageModule(opts);
```

If you agree, I'll make a PR soon.

**Comment by edi9999** [comment]
Yes, totally agree, as it adds the possibility you mentioned without breaking backwards compatibility. 

The PR shouldn't be too complicated, but please also update the readme and the tests :-)
