### ISSUE TITLE
Readme for "quickstart in browser"

### ISSUE THREAD

**Issue by CPonty** [open-xml-templating/docxtemplater-image-module#29]
Can you please create instructions on how to include/build this image module for use in client-side javascript? 

I found the instructions on the main "docxtemplater" project readme very helpful, and am now at the point where I need to start inserting images. I am not using node.js for the server back-end, so having access to the image module in the browser is really a requirement for me to include docxtemplater in my project.

Even really simple bootleg hints would be fine at this point - I need to make sure it's possible before I commit to using your libraries. Thanks!

**Comment by CPonty** [comment]
Based on a cursory look at the source, it looks like you're implementing browser support, but that it's not quite ready yet? Example, stuff like "DocUtils.env = fs.readFile != null ? 'node' : 'browser'" exists, but includes like "http = require('http')" are breaking the browserify build. 

Apologies if I'm misreading this - not really a heavy javascript developer myself.

**Comment by edi9999** [comment]
It should be quite the same than the docxtemplater project:

```
# git checkout v1.0.4 # Optional 
npm install -g gulp jasmine-node uglify-js browserify
 npm install 
gulp allCoffee
 mkdir build -p
 browserify -r ./js/docxgen.js -s Docxgen > build/docxgen.js 
uglifyjs build/docxgen.js > build/docxgen.min.js # Optional
```

You just have to replace ./js/docxgen.js with index.js and Docxgen with ImageModule.

**Comment by edi9999** [comment]
If you find out the exact commands it would be great to create a pull request so that it becomes part of the readme

**Comment by edi9999** [comment]
Add to readme : 0a00b77d4233c06c4240d4a41fd6d8e04943cf83
