### ISSUE TITLE
getImage not called

### ISSUE THREAD

**Issue by simonaberry** [open-xml-templating/docxtemplater-image-module#30]
I managed to build for use in the browser ok (#29). Code is running ok with no errors or warnings.

I have a tag in the template {%image}, but the opts.getImage function is not being called as far as I can see (I put a console log in the function which is not being outputted). 

Any suggestions on how to debug - i.e. what can I check to see were it might be failing. There are not error messages being produced - and the main templating (normal text, not images) is all working fine...

**Comment by edi9999** [comment]
Can you send the code you're using ?

**Comment by simonaberry** [comment]
var opts = {};
	opts.centered = false;
	opts.getImage=function(tagValue, tagName) {
			console.log('processing ', tagValue, tagName); //not called????
			if (tagName === 'progressImg') {
				return images[tagValue];
			}
	};

	opts.getSize=function(img,tagValue, tagName) {
			return [200,30];
	};

	var imageModule=new ImageModule(opts);

	var doc=new Docxgen();
	var data =  {
			'DateGenerated' : dateGen,
			'ProjectName' :$rootScope.projectInfo.name,
			'strats' : strats
			};
	doc.attachModule(imageModule);
	doc.load(content);
	doc.setData(data);
	doc.render();
	var out=doc.getZip().generate({type:"blob"}); //Output the document using Data-URI

**Comment by edi9999** [comment]
I don't see any reasons why this wouldn't work.

Can you upload a zip of your problem with everything needed (docx, js, html, compiledjs )

**Comment by edi9999** [comment]
Closed (not able to reproduce)

**Comment by simonaberry** [comment]
I have finally returned to having a proper look at this and have started to see how the code fits together. Unfortunately I cant easily send you the whole application as it is pretty big.

What is confusing me is that you set up an options object  (that has a `getImage()` function) to pass into the constructor for `ImageModule`. But If I look at the source code for `ImageModule` there is never any call to this function?

I hacked around a bit and replaced 
```
imgData = scopeManager.getValueFromScope(tag);
```
with

```
imgData = this.options.getImage(scopeManager.tags.tagValue,tag)
```
and then I had to bypass  the getImagefromData()
```
    //imgBuffer = this.getImageFromData(imgData);
    imgBuffer = imgData;
```

but I am really stabbing in the dark... I have managed now to get the image tags loading, but I think my data format for the XML is wrong as I just get a placeholder....

**Comment by edi9999** [comment]
I think that you're reading the documentation for the version 1.x (which is not officially released yet), but you're using the 0.x version.

getImage was introduced in version 1.x.

1.x getImage can only get the image synchronously (for now), you should use version 0.x if you want to be able to load the image asynchronously (with an async http request for example).

See this question : https://github.com/open-xml-templating/docxtemplater-image-module/issues/16 for how to asynchronously load an image with version 0.x

**Comment by simonaberry** [comment]
that explains a lot. thanks for pointing out the problem. All working perfectly now
