### ISSUE TITLE
It would be very good to add a built version of docxtemplater-image-module

### ISSUE THREAD

**Issue by morpheus001** [open-xml-templating/docxtemplater-image-module#31]
Hello edi9999,

docxtemplater is really amazing ! Thank you very much for this lib !

In most projects, there is a /build folder where latest builds can be easily downloaded for browser use (even minified builds). The build process creates an unnecessary barrier to adoption.

Can you please add a build folder, as you did it here:
https://github.com/open-xml-templating/docxtemplater-build/tree/master/build

Thank you very much.

morpheus001

**Comment by morpheus001** [comment]
Hello edi9999,

I use Windows 8.1. I work on WinJs with Visual Studio.

I spent 2 days trying to build docxtemplater-image-module with nodejs for windows, without concluding results.

Can you please only put a built version of the current source code here:
https://github.com/open-xml-templating/docxtemplater-build/tree/master/build

Please...Thank you...
morpheus001

**Comment by edi9999** [comment]
Here you have them : https://github.com/open-xml-templating/docxtemplater-image-module-build/tree/master/build

**Comment by morpheus001** [comment]
Hello edi9999,

Thank you very very much !!!

morpheus001
