### ISSUE TITLE
qr image replacement in header fails

### ISSUE THREAD

**Issue by ssured** [open-xml-templating/docxtemplater-image-module#32]
qr image replacement in a header works as long as there is no other (regular) image in the header.

I created a test case in  https://github.com/100y/docxtemplater-image-module/commit/16f387b46ee2545af398115c3febd30ad962f6a6

Any idea where to look to fix this bug? Single QR codes in the header do work

**Comment by ssured** [comment]
ok i did some research; afaik this is what happens

the code parses the `word/header1.xml` first, adding all images to the qrQueue, which it will process one by one. When the queue is empty https://github.com/open-xml-templating/docxtemplater-image-module/blob/6e22c8e3a310dfc3f1f3fc377ff4f522b8a22d5e/coffee/index.coffee#L84 will run and call finished hook.

Then the code will parse the next file, `word/document.xml`, but the finished hook is then already called.

Hope this helps...

**Comment by edi9999** [comment]
They was indeed a problem in the qrQueue, it is fixed now. 

Note that I have also updated the api for the qrcode module , it now uses the options.getImage instead of the getImage attached to the module directly

**Comment by edi9999** [comment]
The Travis ci build fails on node v4 and v5, we must investigate

**Comment by edi9999** [comment]
Fixed :-)

**Comment by ssured** [comment]
Super cool, thanks for fixing!

**Comment by ssured** [comment]
Would you mind releasing this to NPM? as 0.3.5

**Comment by edi9999** [comment]
Hi, this Has been fixed in the master branch, which reflects the upcoming 1.0 release of the image module.

The 1.0 release is not yet ready because it can't handle async images (see #33)

I would accept a pull request with these commits cherry picked to the 0.x branch, and do a new patch release

**Comment by ssured** [comment]
I am a little surprised; I just ran a quick test which allowed me to replace async with the current master, running "docxtemplater": "1.0.5"... 
What I did is add some dummy methods:

```javascript
        var imageModuleOptions = {
          qrCode: true,
          getImage: function() {},
          getSize: function() {},
          getImageAsync: function(imgData, cb) {
...
```

Maybe this is more luck than knowledge?

I'll have a look and see if I can patch the 0.x branch

**Comment by edi9999** [comment]
Indeed, I didn't modify the code for the qrcode part for async, so it is still working.

But this is wip and will be removed once we release 1.0
