### ISSUE TITLE
Strange Square Images

### ISSUE THREAD

**Issue by Taintedmedialtd** [open-xml-templating/docxtemplater-image-module#36]
First off - awesome project, thank you.

I'm having a really strange issue with the image module where images are appearing in the template perfectly square regardless of their aspect ratio and, even more strangely, when you resize them they retain their broken aspect ratio. I've unzipped one of the generated documents and the images contained within are the normal shape and size.

Have you experienced anything like this before? 

I'm using the opts.getSIze function:
    opts.getSize=function(img,tagValue, tagName) {
    	sizeObj = sizeOf(tagValue);
    	var y = sizeObj.height / sizeObj.width * 260;
    	return [260,y];
    }

I've tried all sorts of random numbers in there as well but nothing has an effect on the image size. I am placing several images in to the doc within a loop - could this be a cause?

**Comment by edi9999** [comment]
This is the master branch, which is not completely stable yet (version 1). No npm module has been released to npm yet. For up to date documentation, please switch to the 0.x branch.

The getSize function had an other name in the 0.x version, you're probably using the 0.x version but reading the documentation of 1.x

**Comment by Taintedmedialtd** [comment]
Well I feel like a fool now. I've spent (read wasted) many hours on this and it took 2 minutes to fix. Just in case anyone else does the same thing:

    var imageModule=new ImageModule({centered:false})
    imageModule.getSizeFromData=function(imgData) {
       sizeOf=require('image-size');
        sizeObj=sizeOf(imgData);
        var y = sizeObj.height / sizeObj.width * 260;
        return [260,y];
    }

Thanks for your help
