### ISSUE TITLE
Media files

### ISSUE THREAD

**Issue by awerlang** [open-xml-templating/docxtemplater-image-module#37]
First I'd like to say: Great job you've done so far!

Second, I see there are more media files than there are actual images. I see some `imgData: null` at getImageFromData() (v0.x branch) and then I handle that accordingly. But then there are some 0KB files created nevertheless.

The other thing I noticed is that even for JPEGs, the extension for files in the media folder is always .png. Even still, it works.

While they aren't causing any perceived failures, can we fix that?

**Comment by edi9999** [comment]
I'm not able to reproduce the 0kb images that are created, can you add a test case in a pull request ?

The fact that all files end with .PNG should be changed indeed. I will do it

**Comment by awerlang** [comment]
Perhaps I've experienced the 0Kb images because I'm merging them in a loop...will build a test case anyways.

**Comment by edi9999** [comment]
Any news ?

**Comment by awerlang** [comment]
I've overwritten the method `getImageFromData` this way:

    getImageFromData(imgData) {
        return images[imgData];
    }

Sometimes `imgData` would be `null`. While I noticed this behavior inside a loop, I think it would happen generally.

Perusing the code that handles images we can see this:

    if (imgData === 'undefined') {
      return this.replaceBy(startEnd, tagXml);
    }
    try {
      imgBuffer = this.getImageFromData(imgData);
    } catch (_error) {
      e = _error;
      return this.replaceBy(startEnd, tagXml);
    }

The original method would throw an error instead of just returning `null`.
