### ISSUE TITLE
Different code in latest.min file?

### ISSUE THREAD

**Issue by bythornchris** [open-xml-templating/docxtemplater-image-module#39]
I have got the image module working and it is really neat, but I have a problem with the minified file version.

```docxtemplater-image-module-latest.js``` works great.
```docxtemplater-image-module-latest.min.js``` I get the following error reported using the same html, css and other js files as before.

```
Uncaught SyntaxError: Invalid regular expression: /[\-\.0-9A-Z_a-z\xC0-\xD6\xD8-\xF6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFDÂ·Ì€-Í¯\ux203F-â€]/: Range out of order in character class

docxtemplater-image-module-latest.min.js:12
```
Any ideas?

**Comment by edi9999** [comment]
Is this the file you are using : https://github.com/open-xml-templating/docxtemplater-image-module-build/blob/master/build/docxtemplater-image-module-latest.min.js. ?

Because I don't see those characters in that file

**Comment by bythornchris** [comment]
Yes, I am using that latest file.

On inspecting the non-minified file, I can see
```
23409:  var nameStartChar = /[A-Z_a-z\xC0-\xD6\xD8-\xF6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]///\u10000-\uEFFFF
23410:  var nameChar = new RegExp("[\\-\\.0-9"+nameStartChar.source.slice(1,-1)+"\u00B7\u0300-\u036F\\ux203F-\u2040]");
```

The corresponding bit within the minified file looks like this
```
var nameStartChar=/[A-Z_a-z\xC0-\xD6\xD8-\xF6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]/;var nameChar=new RegExp("[\\-\\.0-9"+nameStartChar.source.slice(1,-1)+"Â·Ì€-Í¯\\ux203F-â€]");
```

Appears that the minifier has screwed up on some of the extended characters in this regex.

**Comment by edi9999** [comment]
I guess it is an issue in uglify, I will try to update the files using uglifyjs2 (uglifyjs is not maintained anymore).

I will let you know

**Comment by edi9999** [comment]
It seems to be related to https://github.com/mishoo/UglifyJS2/issues/902

Does it work on Firefox or chrome ?

I will add the ASCII flag either way

**Comment by bythornchris** [comment]
Hi,

Any news on the updated .min file? Thanks

**Comment by edi9999** [comment]
Should be ok now.
