### ISSUE TITLE
DocxGen is undefined

### ISSUE THREAD

**Issue by hrharshrathi** [open-xml-templating/docxtemplater-image-module#42]
Hello,
while using  'docxtemplater-image-module' module i am getting following error
**error** : 
docx=new DocxGen()
                       ^
ReferenceError: DocxGen is not defined

**this is code :**
var fs = require('fs');
var content = fs
    .readFileSync(__dirname+"/input.docx", "binary");
var Docxtemplater = require('docxtemplater')
var ImageModule = require('docxtemplater-image-module')

var imageModule = new ImageModule({centered:false})

docx = new DocxGen()
    .attachModule(imageModule)
    .load(content)
    .setData({image:'logo.png'})
    .render()

buffer= docx
        .getZip()
        .generate({type:"nodebuffer"})

fs.writeFile("test.docx",buffer);

//**input.docx file contains {%image} tag to append image also**

**Comment by shishir99111** [comment]
facing the same issue!..


var HtmlDocx = require('html-docx-js');
var fs = require('fs');
 var content = fs.readFileSync("input.docx");
                    ImageModule=require('docxtemplater-image-module')
                    var imageModule=new ImageModule({centered:false})

                    docx=new DocxGen()
                        .attachModule(imageModule)
                        .load(content)
                        // .loadFromFile("input.docx")
                        .setData({image:'image.png'})
                        .render()

                    buffer= docx
                            .getZip()
                            .generate({type:"nodebuffer"})

                    fs.writeFile("output.docx",buffer);

**Comment by edi9999** [comment]
The line 



docx = new DocxGen()

Should be

docx = new Docxtemplater()

Docxgen was the old name of the library. I will update the docs for future users

**Comment by shishir99111** [comment]
I tried the same, but now getting this error. 

Error: Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html
    at Object.ZipEntries.readEndOfCentral (../node_modules/jszip/lib/zipEntries.js:149:23)

**Comment by hrharshrathi** [comment]
We tried the same, but now getting this error in **.attachModule(imageModule)**
as 

at Error.XTTemplateError (node_modules/docxtemplater-image-module/node_modules/docxtemplater/js/errors.js:14:24)

**Comment by edi9999** [comment]
Shishir19111 : your docx is invalid. Try to unzip your docx manually and see if it works

**Comment by edi9999** [comment]
Hrharsh : your docx is valid, but the content of the docx is invalid as a template.

If you log the error, you should be able to get an explanation

**Comment by hrharshrathi** [comment]
I have used the Simple docx format which contain only **{%image}** 
but same error occurs 
**error:** 
Can't find endTag


can u plz provide simple short code with docx file

Thanks

**Comment by edi9999** [comment]
There's a test case here https://github.com/open-xml-templating/docxtemplater-image-module/blob/master/coffee/test.coffee

But logging the error should already give you the information
