### ISSUE TITLE
License file missing 

### ISSUE THREAD

**Issue by gad0lin** [open-xml-templating/docxtemplater-image-module#45]
Could you please add License file?

Is it the same license as: https://raw.githubusercontent.com/open-xml-templating/docxtemplater/master/license.md?

**Comment by edi9999** [comment]
Yes, it's the same licence. I will update this

**Comment by edi9999** [comment]
I added the licence file. https://github.com/open-xml-templating/docxtemplater-image-module/blob/master/licence.md
