### ISSUE TITLE
es6 only ?

### ISSUE THREAD

**Issue by smolleyes** [open-xml-templating/docxtemplater-image-module#47]
hi

is there a no es6 version of this module please?

i use it in nwjs and don t want to use nwjs 13 (too buggy) and 0.12 do not support es6 arrow functions

thanks

**Comment by edi9999** [comment]
The npm versions are in es5 (compiled from es6 with babel).

See https://github.com/open-xml-templating/docxtemplater-image-module/blob/master/package.json#L7 if you want to compile it yourself.

**Comment by smolleyes** [comment]
hello

ok with npm
npm install docxtemplater@1.2.1
npm install docxtemplater-image-module@0.3.6

i try to generate my doc now :)
