### ISSUE TITLE
\'tagsXmlArray\' error

### ISSUE THREAD

**Issue by BenYeomans** [open-xml-templating/docxtemplater-image-module#48]
I am trying to output someones signature at the end of a document that is generated using docxtemplater. Here is my code:

`var Docxtemplater = require('docxtemplater');
							var ImageModule = require('docxtemplater-image-module');
							var brokerSignature = brokerName + '.png';
							var pathImage = 'D:/Git/Node/static/dist/img/signatures/' + brokerSignature;
							var opts = {};
							opts.centered = false;
							opts.getImage = function(tagValue, tagName) {
								return fs.readFileSync(tagValue,'binary');
							};
							opts.getSize = function(img, tagValue, tagName) {
								return [150,150];
							};
						
							var imageModule = new ImageModule(opts);
							var doc = new Docxtemplater(options.template);
							doc.attachModule(imageModule);
							doc.setData({
								contact: contact[0],
								image: pathImage,
								from: {
									name: from,
									title: user.Description,
									directLine: user.TelephoneNumber,
									email: user.EmailAddress
								},
								address: {
									main: {
										line1: contact[0].address.main.line1,
										line2: contact[0].address.main.line2,
										city: contact[0].address.main.city,
										stateProvince: contact[0].address.main.stateProvince,
										postcode: contact[0].address.main.postcode,
										country: contact[0].address.main.country
									}
								},
								date: {
									today: moment().format("DD MMMM YYYY")
								},
								other: options.contact
							});
							try {
								doc.render();
							} catch (e) {
								console.log('Render error:', e);
								callback(e, null);
								return;
							}`

and I have {%image} tag in my document however whenever I try to generate the document I get this error: [TypeError: Cannot read property 'tagsXmlArray' of undefined] any idea what I could be doing wrong?

**Comment by edi9999** [comment]
The two versions you are using are probably incompatible. You should use latest versions for both

**Comment by BenYeomans** [comment]
Thanks I wasn't using the latest version of docxtemplater this fixed my issue!

**Comment by BenYeomans** [comment]
Hi Sorry another quick question...

When I get my image generated in the document it doesn't appear because the layout option for it is in line with text so the image doesn't display at all, if I change the layout options (under with text wrapping) and select any of the options the image displays correctly. Is there anyway I can set the layout options with opts object or another way of doing it so the image displays?

**Comment by edi9999** [comment]
I'm not sure exactly how to solve your problem. Can you please send some code with template to reproduce ?

Any way the generated xml can be found here :

https://github.com/open-xml-templating/docxtemplater-image-module/blob/master/es6/index.js#L134

**Comment by edi9999** [comment]
Also please open up a new issue to discuss that, it isn't related at all to your first issue

**Comment by BenYeomans** [comment]
I'll open a new issue with more detail :)
