### ISSUE TITLE
make this work in browser

### ISSUE THREAD

**Issue by akralj** [open-xml-templating/docxtemplater-image-module#5]
Salut,
loading images from server works like a charme in node.js, by adding https://github.com/ForbesLindesay/sync-request
and chaning index.coffee around line 35:

    if imgName.match(/http|https/)
        try
            imgData = request('GET', imgName).getBody()
        catch e
            return @replaceBy('<w:t></w:t>','w:t')
    else
        try
            imgData=fs.readFileSync(imgName)
        catch e
            return @replaceBy('<w:t></w:t>','w:t')

Now I try to make it work in the browers and again everything works, but of couse the images can't get inserted because there are loaded synchronously. So my question is how to change the code that on could load the images async in the browser.
I tried loading them synchronously, but browsers, don't allow to specify a responseType = 'blob' when using  XMLHttpRequest(), synchronosly.
Any ideas would be highly appreciated how to make it work either sync or async. Sync could be done in a web worker later on, that it does not block the browser thread.
mille mercis
andrej

**Comment by edi9999** [comment]
Hi, they are two ways to solve your issue:

1. Make a pull request to support async (it wouldn't be too hard, you should just put a callback instead, and probably add a 'finished' event in the so that you could write something like:

```
ImageModule=require(‘docxtemplater-image-module’)

imageModule=new ImageModule({centered:false})

docx=new DocxGen()
    .attachModule(imageModule)
    .load(content)
    .setData({image:'examples/image.png'})
    .render()

imageModule.on('finished',function(){
  buffer= docx
        .getZip()
        .generate({type:"nodebuffer"})

  fs.writeFile("test.docx",buffer);
})
```

2.The other way would be to do use two docxtemplater. The first one with a fake Image Module, which would get you the names of the images to load. You then load them into memory asynchronously, and when finished, attach a new Image Module to a new docxtemplater which will load the images from memory.

I would rather do 1, because, 2 is a bit hacky, and will maybe not work with future versions of the imageModule.

**Comment by akralj** [comment]
Hi, thank you for your quick response. However I don't see how I could make suggestion 1. work. The code is written completely synchroniosly, so I tried to change it, but failed. Isn't it neccesary to change how the whole module is written? I'm rendering an image loop so I don't see how I could put an finished event in the image module code.
Thank you anyway :)

**Comment by edi9999** [comment]
I think it would make sense to include a promise library such as [Q](https://github.com/kriskowal/q).

The main change would be in the `handle` method:

now we have:

	handle:(type,data)->
		if type=='replaceTag' and data=='image'
			scopeManager=@manager.getInstance('scopeManager')
			templaterState=@manager.getInstance('templaterState')

			tag = templaterState.textInsideTag.substr(1)
			imgData=scopeManager.getValueFromScope(tag)

			tagXml=@manager.getInstance('xmlTemplater').tagXml
			startEnd= "<#{tagXml}></#{tagXml}>"
			if imgData=='undefined' then return @replaceBy(startEnd,tagXml)
			try
				imgBuffer=@getImageFromData(imgData)
			catch e
				return @replaceBy(startEnd,tagXml)
			rId=@imgManager
				.loadImageRels()
				.addImageRels(@getNextImageName(),imgBuffer)

			sizePixel=@getSizeFromData(imgBuffer)
			size=[@convertPixelsToEmus(sizePixel[0]),@convertPixelsToEmus(sizePixel[1])]

			if @options.centered==false
				outsideElement=tagXml
				newText=@getImageXml(rId,size)
			if @options.centered==true
				outsideElement=tagXml.substr(0,1)+':p'
				newText=@getImageXmlCentered(rId,size)


getSizeFromData and getSizeFromData should be async, so instead of returning values, they will return promises.

Eg: for

	getSizeFromData:(imgData)->
		deferred=Q.defer()
		deferred.resolve([150,150])
		deferred.promise


for the handle method, we change from :


			try
				imgBuffer=@getImageFromData(imgData)
			catch e
				return @replaceBy(startEnd,tagXml)
			rId=@imgManager
				.loadImageRels()
				.addImageRels(@getNextImageName(),imgBuffer)

			sizePixel=@getSizeFromData(imgBuffer)
			size=[@convertPixelsToEmus(sizePixel[0]),@convertPixelsToEmus(sizePixel[1])]

			if @options.centered==false
				outsideElement=tagXml
				newText=@getImageXml(rId,size)
			if @options.centered==true
				outsideElement=tagXml.substr(0,1)+':p'
				newText=@getImageXmlCentered(rId,size)


to something like:

	sizePromise=@getSizeFromData(imgData)
	imgPromise= @getImageFromData(imgData)

	success=()=>
		rId=@imgManager
			.loadImageRels()
			.addImageRels(@getNextImageName(),imgPromise.value)
		size=[@convertPixelsToEmus(sizePromise.value[0]),@convertPixelsToEmus(sizePromise.value[1])]
		if @options.centered==false
			outsideElement=tagXml
			newText=@getImageXml(rId,size)
		if @options.centered==true
			outsideElement=tagXml.substr(0,1)+':p'
			newText=@getImageXmlCentered(rId,size)
		
	failure=()=>
		@replaceBy(startEnd,tagXml)

	Q.all([sizePromise,imgPromise]).then(success).fail(failure)

Hope that makes sense.

Can you please update the tests for the async behaviour too ?

**Comment by akralj** [comment]
I changed the code, following your advice and it is working now async using natvie Promises for now. I'm doing a XMLHttpRequest and getting a blob back.

      getImageFromData:(url)->
            deferred=Promise.defer()
            xhr = new XMLHttpRequest()
            xhr.open 'GET', url, true
            xhr.responseType = 'blob'
            xhr.send(null)
            xhr.onload = ->
                deferred.resolve xhr.response
            xhr.onerror = (event) ->
                console.log event
                deferred.reject event
            deferred.promise
So now I don't know what to do with the blob. In which format do I need to convert the image blob, that docxtemplater can consume it?
Thanks again.

**Comment by edi9999** [comment]
Can you please post the code ?

**Comment by akralj** [comment]
I tried to convert the blob reponse to binary data using the FileReader API, but it is not working:
Here the code:

    getSizeFromData:(imgData)->
	    deferred=Promise.defer()
	    deferred.resolve([150,150])
	    deferred.promise
	getImageFromData:(url)->
        deferred=Promise.defer()
        xhr = new XMLHttpRequest()
        xhr.open 'GET', url, true
        xhr.responseType = 'blob'
        xhr.send(null)
        xhr.onload = ->
            reader = new FileReader()
            reader.onloadend = -> deferred.resolve reader.result
            reader.readAsBinaryString(xhr.response)

        xhr.onerror = (event) ->
            console.log event
            deferred.reject event
        deferred.promise

    handle:(type,data)->
        if type=='replaceTag' and data=='image'
            scopeManager=@manager.getInstance('scopeManager')
            templaterState=@manager.getInstance('templaterState')
            tag = templaterState.textInsideTag.substr(1)
            imgName=scopeManager.getValueFromScope(tag)

            if imgName=='undefined' then return @replaceBy('<w:t></w:t>','w:t')

            sizePromise= @getSizeFromData(imgName)
            imgPromise= @getImageFromData(imgName)

            success=()=>
                imgPromise.then (image) => 
                    rId=@imgManager.loadImageRels().addImageRels(@getNextImageName(),image)
                    size=[@convertPixelsToEmus(sizePromise[0]),@convertPixelsToEmus(sizePromise[1])]]
                    if @options.centered==false
                        outsideElement=tagXml
                        newText=@getImageXml(rId,size)
                    if @options.centered==true
                        outsideElement=tagXml.substr(0,1)+':p'
                        newText=@getImageXmlCentered(rId,size)
            failure=()=> 
                console.log "failure"
                @replaceBy(startEnd,tagXml)

            Promise.all([sizePromise,imgPromise]).then(success, failure)
        null

**Comment by akralj** [comment]
but it is not working yet, so I would create a pull request, when it is done. is this ok, with you?

**Comment by edi9999** [comment]
to get the data, I think one way to make it work is to use:

getImageFromData:(url)->
    deferred=Promise.defer()
    JSZipUtils.getBinaryContent('path/to/content.zip', function(err, data) {
       deferred.resolve(data)
    }
    deferred.promise


You need the use the JSZipUtils file https://stuk.github.io/jszip/documentation/howto/read_zip.html

**Comment by akralj** [comment]
Sadly its not working. Tomorrow I will write some tests and compare the file which node fs.readFileSync and the browser xhr.requestType "arraybuffer" produces. Maybe I find the right format.

**Comment by edi9999** [comment]
If you look in the code, the imageManager gives a call to `zip.file(name,data,options)`

https://github.com/edi9999/docxtemplater-image-module/blob/master/coffee/imgManager.coffee#L55-L64

```
file=
'name':"word/media/#{realImageName}"
'data':imageData
'options':
base64: false
binary: true
compression: null
date: new Date()
dir: false
@zip.file file.name,file.data,file.options
```  

If arraybuffer doesn't work, can you please send the generatedfile so I can inspect it ?

http://stuk.github.io/jszip/documentation/api_jszip/file_data.html

**Comment by akralj** [comment]
Salut,
I did not have much time today, so I only figured out how to get arraybuffer images into a jszip. this is working. tommorow i have a look to get it working in docxtemplater.
