### ISSUE TITLE
memory problem with lot of images

### ISSUE THREAD

**Issue by smolleyes** [open-xml-templating/docxtemplater-image-module#51]
hello

me again

i have some troubles when trying to add many images even if i resize them to be small

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

i use this moduel thru nwjs, tried to add js-flag "--max_old_space_size=3500000" (can t add more memory) but still crashing , i think we need to add the image syncronously maybe... ?

i use this code:

```
function genDocx() {
  var DocxGen = require("docxtemplater");
  var ImageModule = require("docxtemplater-image-module");
  var name = path.join(templatesDir,'NOHAP','NOAMIANTE','diag.docx');
  console.log(name)
  rapportObj.imagesRapports=listFileRecursive(rapportsImagesDir)
  rapportObj.planchePhotos=listFileRecursive(photosDir)
  rapportObj.logo = findLogo(rapportsImagesDir);

  var content = fs.readFileSync(name,"binary")
  var doc=new DocxGen(content);
  //set the templateVariables
  var opts = {}
  opts.centered = true;
  opts.getImage=function(tagValue, tagName) {
      return fs.readFileSync(tagValue,'binary');
  }

  opts.getSize=function(img,tagValue, tagName) {
    console.log(img,tagValue, tagName)
    if(tagName === 'logo')
        return [300, 180];
    if(tagValue.indexOf('PHOTOS') !== -1)
        return [150,150];

    return [550,780];
  }

  var imageModule = new ImageModule(opts);
  doc.attachModule(imageModule);
  doc.setData(rapportObj);

  doc.render();

  var buf = doc.getZip()
               .generate({type:"nodebuffer"});

  tmpFile = path.join(generatedDir,'output.docx');
  fs.writeFileSync(tmpFile,buf);
  openHtml()
}
```
for this test i have 444 images for 33.6 mo in size total

an idear ?

thanks !

**Comment by edi9999** [comment]
It seems strange to get an out of memory error for such small data. Can you add a console.log("foo") before render, after render, after getZip() and after generate() to pinpoint exactly where the error happens ?

**Comment by smolleyes** [comment]
hello

think i fixed it...

i tried to display images side by side on a line with 3 cell in my template and so 3 times {%.} and without resizing it, so i had serie of 3 times the same image in my doc ... and it was crashing with more than 5 images.. since i resize the images and use the loop 'normally' i don t have this problem anymore for the moment

maybe it will reappear with a lot of images, will reopen if it s the case 

thanks
