### ISSUE TITLE
print images side by side

### ISSUE THREAD

**Issue by smolleyes** [open-xml-templating/docxtemplater-image-module#52]
hello

could you tell me if it s possible to add images side by side and not one over the other ? 

if i write my template like this {#images} {%.} {/images} i have parse template error :/ 

my goal is to have 3 images by lines

thanks

**Comment by edi9999** [comment]
I don't think it is possible right now.  (Have a look at this : https://github.com/open-xml-templating/docxtemplater-image-module/issues/2 ).

However, you could "simulate this by creating an invisible table (You have to cut the images in groups of 3 images yourself though)

**Comment by smolleyes** [comment]
i found a solution in word... select all images then "insert" menu -> convert text as table then use col = 6 and its ok :) i just had to find the best size for my images (250px width for me)

but still could be an improvement :p

**Comment by edi9999** [comment]
Ok, I'm closing this in favor of #2
