### ISSUE TITLE
Can't load canvas images in word

### ISSUE THREAD

**Issue by MaxiSantos** [open-xml-templating/docxtemplater-image-module#53]
Hi, I'm trying to load canvas images on my docx but I can't. I draw the border of the image and it looks it has the correct dimensions but the image says "Read Error"

[#16](https://github.com/open-xml-templating/docxtemplater-image-module/issues/16) I'm using the methods given in that link: getImageFromData and base64DataURLToArrayBuffer.

This is my code:

`
_getCanvasFromHTML = function (source) {
        var collectionOfDOMImages = _getDOMImages(source);
        Promise.all(_getPromises(collectionOfDOMImages)).then(function (images) {
          _bindImagesToSource(images, source);
          _getFile(source);
        });
      },

_getPromises = function (imagesDOM) {
        var promises = [];
        for (var i = 0; i < imagesDOM.length; i++) {
          (function (element){
            promises.push(new Promise(function (resolve) {
              html2canvas(element.domElement, {
                onrendered: function (canvas) {
                  resolve({
                    canvas  : _processImage(canvas.toDataURL('image/png'), canvas.width, canvas.height),
                    position: element.position,
                    section : element.section
                  });
                }
              });
            }));
          })(imagesDOM[i]);
        }
        return promises;
      },

_processImage = function (image, width, height) {
        var imageProcessed;
        switch(_config.typeOfFile){
          case "word":
            imageProcessed = {
              image       : KW.helper.Tools.base64DataURLToArrayBuffer(image),
              canvasWidth : width,
              canvasHeight: height
            }
            break;
          default:
            imageProcessed = image.canvas;
            break;
        };
        return imageProcessed;
      },

`

In the project there is already other implementation (and it's working) that handle the word download but I'm trying to make something more generic. For all the pages in the app. Could it be related with the fact I'm using promises and for some reason the canvas are not ok ? Any help/guide will be very appreciated please.

**Comment by edi9999** [comment]
Docxtemplater-image-module only handles values, not promises.  I don't see the definition of getImageFromData in your code, did you forgot to include it ?

**Comment by MaxiSantos** [comment]
Thanks edi9999.

Yes, I'm using the getImageFromData as it's on #16. 

`
 ImageModule.prototype.getImageFromData = function(imgData) {
     /**
    *   Modified in order to handle canvas dataToURI images :
    *   https://github.com/open-xml-templating/docxtemplater-image-module/issues/16
    *   https://github.com/open-xml-templating/docxtemplater-image-module/issues/5
    *   return fs.readFileSync(imgData);
    **/
    return imgData;
  };
`

I'm using [html2Canvas](https://html2canvas.hertzen.com/) to get some images from some pages on my app. I also use promises to handle all images in a better way (in my opinion) following this approach [using promises with html2canvas](https://codedump.io/share/UM06lvVEanKe/1/callback-after-two-asynchronous-functions)

On the "then" of the Promises I call _getFile(source). Source is a json object that basically has the structure that match the template of my docx with all the images supposedly converted to ArrayBuffer format when I called _processImage.

Any guide of where I can debug/search to find what the issue I'm facing is would be appreciated. I think the issue is related with the convertion. I'd say I'll start searching how to see the content of an ArrayBuffer to see if my image is stored correctly before I try to convert it to a docx. But if you know something please let me know.

Thanks in advance.

**Comment by MaxiSantos** [comment]
Based on this link [saving canvas](http://stackoverflow.com/questions/17332071/trying-to-save-canvas-png-data-url-to-disk-with-html5-filesystem-but-when-i-ret) I used the first solution on the post to check if my ArrayBuffer is correct or not. In that solution he's using a Blob object but based on the ArrayBuffer. I did that and I can see my images so I assume my ArrayBuffer is correct. And that arrayBuffer is what I'm sending to docxtemplater-image-module.

**Comment by MaxiSantos** [comment]
So far I'm stuck in this:
```javascript
ImageModule.prototype.replaceTag = function() {
var e, imageRels, imgBuffer, imgData, newText, outsideElement, rId, scopeManager, size, sizePixel, startEnd, tag, tagXml, tagXmlParagraph, templaterState;
    scopeManager = this.manager.getInstance('scopeManager');
    templaterState = this.manager.getInstance('templaterState');
    tag = templaterState.textInsideTag.substr(1);
    imgData = scopeManager.getValueFromScope(tag);
    tagXml = this.manager.getInstance('xmlTemplater').tagXml;
    tagXmlParagraph = tagXml.substr(0, 1) + ':p';
    if (this.options.centered === false) {
      outsideElement = tagXml;
    }
    if (this.options.centered === true) {
      outsideElement = tagXmlParagraph;
    }
    startEnd = "<" + tagXml + "></" + tagXml + ">";
    if ((imgData == null) || imgData === 'undefined') {
      return this.replaceBy(startEnd, outsideElement);
    }
    try {
      // old
      // imgBuffer = this.getImageFromData(imgData);
      // new
      imgBuffer = this.getImageFromData(imgData.image);
    } catch (_error) {
      e = _error;
      return this.replaceBy(startEnd, tagXml);
    }
    imageRels = this.imgManager.loadImageRels();
    if (imageRels) {
      rId = imageRels.addImageRels(this.getNextImageName(), imgBuffer);
      sizePixel = this.getSizeFromData(imgBuffer);
      size = [this.convertPixelsToEmus(sizePixel[0]), this.convertPixelsToEmus(sizePixel[1])];
      if (this.options.centered === false) {
        newText = this.getImageXml(rId, size);
      }
      if (this.options.centered === true) {
        newText = this.getImageXmlCentered(rId, size);
      }
      return this.replaceBy(newText, outsideElement);
    }
```
When I go imgData.image.byteLength it returns zero. Then it makes sense later it creates a docx file with broken images. But this is weird,

```javascript
// 01 - this parsedObject contains my ArrayBuffer and I can see the content is there
docx.setData(parsedObject);

// when I debug it, this render method at some point calls replaceTag and there my
// ArrayObject.byteLength returns zero
docx.render();

// but when I continue the flow in this line if I want to see the content of parsedObject I can see it.
output = docx.getZip().generate({type:"blob"});
```
I don't know if the image-module is deleting the reference of my ArrayObject... any ideas ?

**Comment by edi9999** [comment]
They was a performance issue at version 2.0 and before of docxtemplater. The underlying issue was that I was deep cloning the tags when looping over then. Cloning of array buffers was probably not working with my implementation. Updating to 2.1 can maybe solve your issue

**Comment by MaxiSantos** [comment]
Hi. Yes, 2.1 seems to solve the issue with array buffers. But docx-image-module is only compaatible with version 2 of doctemplater

It's throwing an exception at this point:

ImageModule.prototype.replaceTag = function() {
....
tagXml = this.manager.getInstance('xmlTemplater').tagXml;
tagXmlParagraph = tagXml.substr(0, 1) + ':p';

-- tagXml is undefined and it fails on substr.

**Comment by MaxiSantos** [comment]
Well, as a quick fix what I did is this. I'm using stable version of both but now on the docxgen I added a filter for the arrayLength object using the byteLength property. It's dirty but it saves me for now.

```javascript
DocUtils.clone = function(obj) {
  var flags, key, newInstance;
  if ((obj == null) || typeof obj !== 'object' || obj.byteLength>0) {
    return obj;
  }
  if (obj instanceof Date) {
    return new Date(obj.getTime());
  }
  if (obj instanceof RegExp) {
    flags = '';
    if (obj.global != null) {
      flags += 'g';
    }
    if (obj.ignoreCase != null) {
      flags += 'i';
    }
    if (obj.multiline != null) {
      flags += 'm';
    }
    if (obj.sticky != null) {
      flags += 'y';
    }
    return new RegExp(obj.source, flags);
  }
  newInstance = new obj.constructor();
  for (key in obj) {
    newInstance[key] = DocUtils.clone(obj[key]);
  }
  return newInstance;
};
```

**Comment by edi9999** [comment]
The latest versions should be
Working together, you should update the image module too. See https://travis-ci.org/open-xml-templating/docxtemplater-image-module for proof
