### ISSUE TITLE
img in loop ?

### ISSUE THREAD

**Issue by smolleyes** [open-xml-templating/docxtemplater-image-module#55]
hello

can t we do something like this ?

{#list}

{astring}

{%img}

{/list}

where the list is for exemple

[{astring:'truc1',img:'/home/xx/xx.png'},{astring:'truc2',img:'/home/xx/xx2.png'}]

when i do this i always have an error : "Cannot read property 'length' of undefined"

thanks

**Comment by edi9999** [comment]
The template looks correct. There's a test case here , maybe you could create a failing test case for your issue ? https://github.com/open-xml-templating/docxtemplater-image-module/blob/master/es6/test.js#L115

**Comment by wautersN** [comment]
having the same issue.

**Comment by wautersN** [comment]
Found the sollution! 

This wil solve the case https://github.com/open-xml-templating/docxtemplater-image-module/issues/57

**Comment by edi9999** [comment]
Corrected in https://github.com/open-xml-templating/docxtemplater-image-module/commit/b08331365221d7914a9ada6d5ab1d4121b1bd63b, released in v1.0.1
