### ISSUE TITLE
Images looping within nested objects

### ISSUE THREAD

**Issue by AlexanderRatomski** [open-xml-templating/docxtemplater-image-module#57]
Hello,

I tried to display images in the loop (angular-expressions module was added):

{#report.sales_comps.comps}
{%image}
{/report.sales_comps.comps}

And got error: 
![image](https://cloud.githubusercontent.com/assets/3540748/14495281/738f8fb0-0197-11e6-8688-bcdc50884e3b.png)

After debugging I found the reason:
![image](https://cloud.githubusercontent.com/assets/3540748/14495316/969653cc-0197-11e6-884c-ad60e7810807.png)

I just moved the declaration upper and it helped me.

**Comment by edi9999** [comment]
Indeed, this seems to be a bug, thanks for reporting it

**Comment by edi9999** [comment]
Corrected in https://github.com/open-xml-templating/docxtemplater-image-module/commit/b08331365221d7914a9ada6d5ab1d4121b1bd63b, release in v1.0.1
