### ISSUE TITLE
PPTX Example

### ISSUE THREAD

**Issue by raminahmadi1986** [open-xml-templating/docxtemplater-image-module#59]
Hi ,
I need an example of inserting image in a pptx file (browser), I've tried many ways , but non of them worked !

**Comment by edi9999** [comment]
The current image-module doesnt' support pptx at all. They is an open pull-request https://github.com/open-xml-templating/docxtemplater-image-module/pull/12 that is quite old, I had some comments about it but the opener of the PR didn't make the requested changes. 

You are free to reopen a new pull request to fix the issues with the old PR.

**Comment by raminahmadi1986** [comment]
@edi9999  , Isn't there any way to add a simple image to a slide ?? I don't know how to fix it

**Comment by edi9999** [comment]
No they is no way with the current code can generate images in pptx
