### ISSUE TITLE
Word message : Ambiguous cell mapping encountered

### ISSUE THREAD

**Issue by nicolas824** [open-xml-templating/docxtemplater-image-module#64]
Salut,
I'm trying to embed your solution in Ionic App. System is working pretty good to add text contents but, when I try to add images, when I try to open generated document, I have this message :

_Ambiguous cell mapping encountered. Possible missing paragraph element. &lt;p&gt; elements are required before every &lt;/tc&gt;_

and picture doesn't appear

    loadImg('img/add.png', function() {
        createDoc();
    });

    function createDoc() {
    var opts = {}
    opts.centered = false;
    opts.getImage=function(tagValue, tagName) {
        return getBase64Image(myimg);
    }    
    opts.getSize=function(img,tagValue, tagName) { 
        return [200,200];
    }

    var imageModule=new window.ImageModule(opts);

    var loadFile=function(url,callback){
        JSZipUtils.getBinaryContent(url,callback);
    }

    loadFile("templates_doc/test.docx",function(err,content){
        if (err) { throw e};
        // doc=new Docxgen(content);
        doc=new Docxtemplater(content);

        doc.attachModule(imageModule);
        doc.setData( {"text1":"text_message",
                "myimage":"img/add.png",
            }
        );
        doc.render() ;
        out=doc.getZip().generate({type:"blob"});
        saveAs(out, 'output.docx');
        }

Merci pour ton aide,

**Comment by edi9999** [comment]
The problem comes from docxtemplater, and is already reported here : https://github.com/open-xml-templating/docxtemplater/issues/226. The author of the issue also proposes some code to fix the issue.

I'm closing this to avoid duplicates. If you wish to work on a PR in docxtemplater, you're welcome :-) .
