### ISSUE TITLE
Word : This image cannot currently be displayed

### ISSUE THREAD

**Issue by nicolas824** [open-xml-templating/docxtemplater-image-module#65]
Salut,

I'm trying to embed your solution in Ionic App. System is working pretty good to add text contents but, when I try to add images, when I try to open generated document, instead to see picture, I see this message :

![capture d ecran 2016-08-13 a 10 39 18](https://cloud.githubusercontent.com/assets/10085142/17642352/458cce2e-6142-11e6-8f1c-5de728859ad7.png)

```

    loadImg('img/add.png', function() {
        createDoc();
    });


function createDoc() {
var opts = {}
opts.centered = false;
opts.getImage=function(tagValue, tagName) {
    return getBase64Image(myimg);
}    
opts.getSize=function(img,tagValue, tagName) { 
    return [200,200];
}

var imageModule=new window.ImageModule(opts);

var loadFile=function(url,callback){
    JSZipUtils.getBinaryContent(url,callback);
}

loadFile("templates_doc/test.docx",function(err,content){
    if (err) { throw e};
    // doc=new Docxgen(content);
    doc=new Docxtemplater(content);

    doc.attachModule(imageModule);
    doc.setData( {"text1":"text_message",
            "myimage":"img/add.png",
        }
    );
    doc.render() ;
    out=doc.getZip().generate({type:"blob"});
    saveAs(out, 'output.docx');
    }
```

Merci pour ton aide,

**Comment by edi9999** [comment]
Can you log  `getBase64Image(myimg);` ? My guess is that it returns an empty string.

**Comment by nicolas824** [comment]
Hi,

This log

```
opts.getImage=function(tagValue, tagName) {
  console.log(getBase64Image(myimg));
  return getBase64Image(myimg);
}
```

display

_iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAJXUlEQVR4Xu2dWaxkVRWGv+WAEwIKziLaRlvRAAbjjEGNEo1ThDhEw4MapwcTjcGYEB8MidEYSXxwivqAEIeIAxoNGkecEwWN3UJHFG0Vu2lpbBsEFLf5Kqvaqnur+p6qU6em3ivZqZubfU6dWv/Za629ph0sCZVS7gacANwPeDDw8Bz3BY4H/Lw3cAxwT8D5d8nH/w9wG3ALcAD4J3Aj8Pf8vA5w/BW4AdgXEc5fOMUin6CUclfgKMDPo4H7Aw8AHgKcBDwsGS/z75MACIIAeM0g/TsBkPmO/cl8gfgT8EfgL8AeYC9wEPCa2yPCz4XQogGQ0ScDjwa255vv/44D7pFDRvfHnQfe+nEMczXckcyVsY5/5bgpQXAlXAPsAnZGhMAshOYKQIoZ3/ITczwOeCywLcWNjL9Tx5z4LyAQiqTfA78FdgC7c+ydp3iaGwCllLsDjwGeBjwr/1bM+Kb7HIOjSwwKMDhcHYqnq4HvAj/274i4tcuH6N+7cwBKKSpV3/QnAaeluFHBqliXiVTYrgrF0lXAz10ZEaHS7ow6AaCUonWiUlXU+MY/AzgTeGhnv2S2N/4z8D3gh7kiFE8HI0L9MlPqCgAtmWcCz08AfNuPHWG5zPTHzPBmKu5/pBmrSPoG8IOI0IKaKc0UgFKKpuIjgefmG6/YUbGuMqmwFUeuiG8B10aEJu5MaGYAlFK01Z8KvBh4QdryM7v/TH7t9DdRaWuqfh24DPhJRLi/aE0zYVApxQ3Ti4CXpF2vLb+OJAg7ga8AX40IN3itqBUApRR3pG6iFDmvAE5v9TSrc/EvgM+lSNoVEbpApqK2AJwKvDrffC0ebfojgdw7aBm5Ei6JiF9N+6OnAiDf/CcAL0vmq3iPRLo2QfgicOU0K2EiAEopztcfo3XzmlS46yrvm75Q6gUV88VpLd0RESrtRjQpAPppTgHOBc5J55mAHMmk40/n3heAi4BfR4T+pkbUGIB0HetSeCXwcuARjb7hyJn0B+DzwGfThdHIxT0JAJqaWjqvS+/lRn/8kcPq0b9Uhutd/aQWUlMTtREAucN9FfB6QOVbaTwHrgQ+AXymyY55SwBKKfpwng68I93Ilflbc0C39geAH0WEPqWx1AQAN1dvAl4IPHDr764zgL8BXwM+GhFu2iYHoJSixWP06rXAW9K3U7nbnAOapx8GPmUMepxlNHYFpOg5K+X+c+YQKmz+01Zjpqbot1MfXD5OFB0OgMcDbwNempkJq/Gzl+sp9Zh+GbgwIn4z6tFGAlBKMYBydgJgHLfS9Bww1nwhcGlEGPYconEAnJGK93mZLDX918/wyt3XXMfHzn3f2Duedd45nHG20nKpaB/wzVTIV2wJQCnlXsBbU/Fq9fSzzxb+q1YUAOPIWkUq5A9FxM2DjBxaAZm3o8h5V+56F870wQdYUQD6P8H4wXsz5eVQWuRGAB6U7uU3LOOOd8UBcIf8cd3XEXF9H5WNAJhCouVj4tSy5e2w4gCogN0haxGZadGjjQDo6Tw/8zSXRvb3H3bFAVAXmI96QUToMf0/AJlIZQbbm4G3AyripaMVB0B+qoA/CHzENHkTvXorIC0fU0qU/YYZlzLIsgYAGLwxfKkuMLXl5j4AFj0YYtTXr7t5SyfdIpbHGgBgqFJlbMzg4og4EJm1rPg5LzMcdD93nSI+FX5rAID+Id3TlwDv74mhUorlQG64VL5mtcn8ugKmekW2vMgVIAgG8S9wgyYA5vYIwruBp2x5iwVOWIMV0OfeT4H3GMwXAPM4BUDrx2qVpaU1AsCqHK2hHgAGWxRBpppYsbK0tEYAWJFjCktPBKkMBMDgixGwpaU1AsAqzcv7ABjBt6BCN4Qp5ktLawSAgRrdEXtcAV9KAIyAWYO7tLRGAFjHbISsB8D3U/RYOGcl49LSGgFgBaYFgXsF4JfZHkBX9FK6IPpvxBoBoEtCl3RvI/a7BEDx08kG7Pwn6+NbLXrjRe/kxO0KhU7IDZliqAeAmb02yegs17MCMBJEc0n3CYCBAqsbO3n7/eoKwEgAXAX7BUDnkN7QzqgCMJa1PW9oBWAEfzrWAf1v7AFQRdBiADgkgqoSXgwAh5Rw52boFZeao9qebrr+Rn726e+MvdGjnn0K255o2XJ7OvXM0znm+M66LAyZoXUj1h6vSe8wtBGrrohJ2dd+/pArojrj2jN00jsMOeOqO3pS9rWfP+SOrgGZ9gyd9A5DAZkakpyUfe3nD4Uka1C+PUMnvcNQUL6mpUzKvvbzh9JSamJWe4Y2vcPIxCzDkDU1sSkL283bnJro/UopNTm3HWObXr05OTcBsB6gpqc3ZeP088amp1sNUws0pmds0ytHF2j0ry6l1BKlpqycfN74EqUBAGqR3uSMbXpFoyK9WqbalJ2Tz2tUpuq5LLVQe3LmNrli60LtAYuotipowtJmc5q3KhjQBUvZrOO2W25l727bLoymY084rsswYjN2b541WbOOXAW1Xc207N583eTtahKE2rCpPQjTNWxKACxXrS3Lpgehdcuy2rRveuZ7ZbumfQMKubatnByI9m0rBwCojVsnB2B2jVtTH5i+XlsXNwNitq2LB1ZCbd59eAC6a96dq8AKmtq+fjwI3bavTxDqAQ6bAZjPAQ4JQD3CZDMA8zvCZEAfeHxVPcQH5nuIz0bws9VNPcZq3sdYbVgJ9SC3RR3ktsFErUcZNtsnDM2aWW1wPcxzCu7Puji7Hmc7OQgzWwGDX11KqQc6N8SiKwDqkeaLBGDDajDjTheG50+elsff2oZk2ZqDm7djD59dwFV5LuSOiLihIS+nmtbJChj1JNkg1pQXk7/szu7fNgn0CFyfY3BM9WMaXmSC7ODwaForVozd6ka2ldjVEWElY+c0NwDSlWHekY0BPXvY4cqwVeY2wFVhZXTXXXsNFXpOvG+7Rw9arbIjzwf2jGCPnDp0wELXCMwVgBE7aY/CPTnF0vbsX+r/BMKV4dAL2x929Nqqrb55ODrIdA/3h2+5Q8bru7E9g63kFTc7I8L/LYQWDYCMPSoZfHSuDi0oQVA8GYOwk6PDoJBdvRz6ojY2mJLZHi1uDa5jP2BWgsOz3xUzMnqPbzlwMAG6PSIanXzaBUILBWCDslY82blLpW3ZlCLJIfNV2H7KfItJBMD5/dXgW6/YEIADCYCMV7H6qbhx+OarVPfNU8wcDrj/ASyWKlvWBwyAAAAAAElFTkSuQmCC_

**Comment by nicolas824** [comment]
Hi,

I just turn base64 to true as specified here : #44 
Thx for your work ;-)

**Comment by edi9999** [comment]
I think it should work if you just return myimg without changing docxtemplater's code

**Comment by Naveen-ASI** [comment]
![image](https://cloud.githubusercontent.com/assets/26600437/24239826/65a79382-0fd5-11e7-9e73-e768028569ba.png)
any one help in this problem
