### ISSUE TITLE
Image Styles

### ISSUE THREAD

**Issue by simonaberry** [open-xml-templating/docxtemplater-image-module#67]
Is it possible to add an image style (e.g. drop shadow) to the tag ?

**Comment by edi9999** [comment]
This is not possible right now. 
Here is how you could change it by changing the code : 

https://github.com/open-xml-templating/docxtemplater-image-module/blob/master/es6/index.js#L141

**Comment by edi9999** [comment]
The way to do this is probably to use the qr-code module, which is a paid module : 

https://modules.docxtemplater.com/
