### ISSUE TITLE
FATAL ERROR - when dealing with a large .docx

### ISSUE THREAD

**Issue by Lennyman** [open-xml-templating/docxtemplater-image-module#73]
Is there any way I can prevent a fatal error being thrown when dealing with a large .docx?

I tried firing off node with 4Gb memory, but it still threw the following at .render() :-

<--- Last few GCs --->

  300756 ms: Mark-sweep 1379.2 (1426.5) -> 1378.1 (1437.5) MB, 611.7 / 0.0 ms [allocation failure] [scavenge might not succeed].
  301466 ms: Mark-sweep 1390.7 (1437.5) -> 1390.7 (1437.5) MB, 705.7 / 0.0 ms (+ 0.1 ms in 202 steps since start of marking, biggest step 0.0 ms) [allocation failure] [scavenge might not succeed].

<--- JS stacktrace --->

I don't mind reporting back to the user "Sorry... it's too big!", but I need to determine that _before_ it throws a fatal error 😞

**Comment by Lennyman** [comment]
Oops - This is nothing to do with your addon - it's the main module. Sorry!

**Comment by edi9999** [comment]
Thanks for moving it in the right issue tracker :-)
