### ISSUE TITLE
header on each image in a loop

### ISSUE THREAD

**Issue by harmon25** [open-xml-templating/docxtemplater-image-module#75]
Trying to do the following in a template:
```
{#diagrams}
{header}

{%diagram}

{/diagrams}
```
-  `diagrams` is an array of objects: `{header: "some header", diagram: "/some/image/path"}`
-  am getting the images inserted into the document, but not the header text
- using v3 of this module and docxtemplater
- node 7.2

Am I doing something wrong?
Or a weird interaction between this and the main module?

**Comment by harmon25** [comment]
Managed to solve my problem with this in the template:
```
{#diagrams}
{@header|rawHead}

{%diagram}

{@empty|raw}
{/diagrams}
```
- `@header|rawHead` is raw XML styled with `Heading4`
- `@empty|raw` is placing an empty paragraph after the diagram: `<w:p></w:p>`

This lets me loop over the images, placing a styled paragraph on top as a heading for each image.

This is a bit of a hack to get the output I wanted, not sure if there is a better way to achieve the intended output...

**Comment by edi9999** [comment]
Thanks for submitting this report. This has been fixed in docxtemplater itself, please upgrade to docxtemplater 3.0.2

**Comment by harmon25** [comment]
Awesome, works great.

Thanks!

**Comment by edi9999** [comment]
Great !
