### ISSUE TITLE
Issue in loading images in loop

### ISSUE THREAD

**Issue by harshrathi-sdn** [open-xml-templating/docxtemplater-image-module#76]
Hi please check my code 
var opts = {}
    opts.centered = true;
    opts.getImage = function (tagValue, tagName) {
        console.log(tagValue)
        return fs.readFileSync(tagValue, 'binary');
    }
    opts.getSize=function(img,tagValue, tagName) {
        return [50,50]
    }
    var imageModule = new ImageModule(opts);
    var zip = new JSZip(content);
    var doc = new Docxtemplater()
        doc.attachModule(imageModule)
           .loadZip(zip);
    var data = [
            {'d':1,'img':'img1.png'},
            {'d':2,'img':'img2.png'},
            {'d':3,'img':'img3.png'}
            ]
    doc.setData({data:data})
    doc.render();

    var buffer= doc.getZip().generate({type:"nodebuffer"});
    fs.writeFile("test.docx",buffer);

and in docx template, I have written 
**{#data}
{%img}
{/data}**

**Error is**
Error: Raw tag not in paragraph from "/node_modules/docxtemplater/js/traits.js:15"

**Comment by devendrak-sdn** [comment]
Yes, I got the same issue, when I loop it over the image object.
I had tried both ways:-
1. {#data}{%img}{/data}
2. {-w:p data}{%img}{/data}
But nothing works, 
When I go ahead with single image it is working fine.
Please suggest solution...

**Comment by devendrak-sdn** [comment]
I got it, Should be new line before and after the img tag.
Example:-
{#data}

{%img}

{/data}

**Comment by edi9999** [comment]
Thanks for submitting this report. This has been fixed in docxtemplater itself, please upgrade to docxtemplater 3.0.2
