### ISSUE TITLE
question does it support image in pptx? 

### ISSUE THREAD

**Issue by andypeng2015** [open-xml-templating/docxtemplater-image-module#78]
hi,
does it support image in pptx and what's the alternative if it's not supported yet, i only need to insert one png base64 blob to pptx, kindly share the example code

thanks

**Comment by edi9999** [comment]
Yes, it now supports pptx image insertion. You can try it by using the master branch.

I will release a new version on npm next week

**Comment by andypeng2015** [comment]
hi @edi9999 thx a lot, could you please ptovide a demo of how to insert png to pptx?

**Comment by andypeng2015** [comment]
[docxtemplater-image-module-latest.js.txt](https://github.com/open-xml-templating/docxtemplater-image-module/files/752419/docxtemplater-image-module-latest.js.txt)
[docxtemplater.v3.0.0.js.txt](https://github.com/open-xml-templating/docxtemplater-image-module/files/752420/docxtemplater.v3.0.0.js.txt)

docxtemplater and image module js files

**Comment by edi9999** [comment]
Please retry, with docxtemplater latest v3.0.3. it has been fixed I think

**Comment by andypeng2015** [comment]
hi @edi9999 still the same error `TemplateError: Raw tag not in paragraph`

[docxtemplater.v3.0.3.js.txt](https://github.com/open-xml-templating/docxtemplater-image-module/files/752690/docxtemplater.v3.0.3.js.txt)
[docxtemplater-image-module-latest.js.txt](https://github.com/open-xml-templating/docxtemplater-image-module/files/752691/docxtemplater-image-module-latest.js.txt)

**Comment by edi9999** [comment]
You have to compile docxtemplater-image-module yourself since it is unreleased yet. Latest image module corresponds to the latest release, not master

**Comment by andypeng2015** [comment]
hi @edi9999 i use docxtemplater-image-module-build to build the latest module? is it correct? I thought it will clone the latest release and build thanks

**Comment by edi9999** [comment]
You have to look at bin.bash in the build repository and execute the commands for the master version of docxtemplater

**Comment by andypeng2015** [comment]
hi @edi9999 i did check out the latest master version then `npm run preversion` , but still same error, pls refer to the log, thanks

[log.txt](https://github.com/open-xml-templating/docxtemplater-image-module/files/752984/log.txt)

**Comment by edi9999** [comment]
Can you share your template and data

**Comment by andypeng2015** [comment]
hi @edi9999 template is in the zip file, and opts.getImage returned is in png-base64.txt, png-base64-raw.txt is complete data with `data:image/png;base64,`


[png-base64.txt](https://github.com/open-xml-templating/docxtemplater-image-module/files/753010/png-base64.txt)
[png-base64-raw.txt](https://github.com/open-xml-templating/docxtemplater-image-module/files/753011/png-base64-raw.txt)

 

[my.zip](https://github.com/open-xml-templating/docxtemplater-image-module/files/753008/my.zip)

**Comment by edi9999** [comment]
When I try to do it , I don't get any kind of errror (and the image is shown).

Also, you shouldn't put any other text in the same area where you put the {%myImage}, because the full container will be deleted (in PPTX, images are not inlined but are seperate elements that can be placed as you wish.nn

**Comment by edi9999** [comment]
I have just release v3.0.1, which now contains the latest feature

**Comment by andypeng2015** [comment]
hi @edi9999  i tried v3.0.1 but still the same error `TemplateError: Raw tag not in paragraph`, my complete data and template attached, pls kindly take a look, thanks a lot in advance.

[my.zip](https://github.com/open-xml-templating/docxtemplater-image-module/files/753543/my.zip)

[code.txt](https://github.com/open-xml-templating/docxtemplater-image-module/files/753544/code.txt)
[data.json.txt](https://github.com/open-xml-templating/docxtemplater-image-module/files/753545/data.json.txt)

**Comment by edi9999** [comment]
@andypeng2015 Please stop duplicating your posts, it is very annoying !!

I will respond in the other issue.
