### ISSUE TITLE
not functioning when using extra module image-size

### ISSUE THREAD

**Issue by giokara** [open-xml-templating/docxtemplater-image-module#81]
Using this module in combination with the image-size module, as explained in the documentation, does not work for me. The code is run without any errors, but no image is added to the word template. The image-size module works fine when used independently. Also, changing the opts.getSize function to return a constant size array (e.g. [100, 100]) adds the image as expected.

Below is the MWE I used:

    var fs = require("fs");
    var Docxtemplater = require("docxtemplater");
    var ImageModule = require("docxtemplater-image-module");
    var JSZip = require("jszip");
    var sizeOf = require("image-size");
    
    var write = function (data) {
        // image specific options
        var opts = Object.create(null);
        opts.centered = false;
        opts.getImage = function (tagValue, tagName) {
            return fs.readFileSync(tagValue, "binary");
        };
        opts.getSize = function (img) {
            sizeObj = sizeOf(img);
            console.log(sizeObj);
            return [sizeObj.width, sizeObj.height];
        };
        fs.readFile("template.docx", "binary", function (err, content) {
            if (err)
                console.log(err);
            var zip = new JSZip(content);
            var imageModule = new ImageModule(opts);
            var doc = new Docxtemplater()
                .attachModule(imageModule)
                .loadZip(zip)
                .setData(data)
                .render();
            var buf = doc.getZip().generate({ type: "nodebuffer" });
	    
            fs.writeFile("result.docx", buf, function (err) {
                if (err)
                    console.error(err);
                console.log("printed file");
            });
        });
    };
    
    var myDate = new Date().toISOString();
    write({ logo: "dummy-logo.png", firstName: "John", lastName: "Smith", date: myDate });
    
    console.log("output image-size using file name: " + JSON.stringify(sizeOf("dummy-logo.png")));
    var img = fs.readFileSync("dummy-logo.png", "binary");
    console.log("output image-size using binary data: " + JSON.stringify(sizeOf("dummy-logo.png")));

**Complete MWE:**

[mwe.zip](https://github.com/open-xml-templating/docxtemplater-image-module/files/773665/mwe.zip)

**Comment by ddimka** [comment]
Try 
**sizeObj = sizeOf(tagValue);**
instead of 
**sizeObj = sizeOf(img);**

**Comment by giokara** [comment]
Thanks, this solves the issue!

I had looked a little bit into the error myself in the meanwhile. It seemed to be an issue in the render() function of the ImageModule class in index.js. Below the stack trace I got when removing the try-catch statement in that function, thought that it might still be interesting...

    Error: Path must be a string without null bytes
        at nullCheck (fs.js:135:14)
        at Object.fs.openSync (fs.js:639:3)
        at syncFileToBuffer (<path>/node_modules/image-size/lib/index.js:57:23)
        at module.exports (<path>/node_modules/image-size/lib/index.js:99:18)
        at opts.getSize (<path>/writer2.js:16:19)
        at ImageModule.render (<path>/node_modules/docxtemplater-image-module/js/index.js:142:33)
        at moduleRender (<path>/node_modules/docxtemplater/js/render.js:10:28)
        at <path>/node_modules/docxtemplater/js/render.js:25:24
        at Array.map (native)
        at render (<path>/node_modules/docxtemplater/js/render.js:24:26)

**Comment by edi9999** [comment]
The real issue is I think the try catch, it willl be removed in the next version so that errors are not suppressed.

**Comment by edi9999** [comment]
Try catch issue resolved : https://github.com/open-xml-templating/docxtemplater-image-module/commit/ab1881174768222d3a5ba173f24c26fe8e8d9809
