### ISSUE TITLE
repeat different images on browser

### ISSUE THREAD

**Issue by Naveen-ASI** [open-xml-templating/docxtemplater-image-module#84]
I have more that one chart in my webpage and i need to convert that into image and create doc from them. I successfully repeated the single chart but i was failed to do different chart. i can attach image module one time . how do I attach different image module and render them at same time on browser

**Comment by edi9999** [comment]
You dont have to attach the module multiple times. 

You can do : 

```
doc.setData({
  images:[ 
     im: "image1"
  }, {
     im: "image2"
  }
]})

moduleOptions = {
 getImage: (im) => images[im]
}
```

You just have to fill the images object.

You can write in your template: 

```
{#images}
{%im}
{/images}
```

**Comment by Naveen-ASI** [comment]
I have two images: 'image1.png', 'image2.png'. Created one function for imageOptions:

                   function getImageOptions(imageURL){
				var promise = new Promise(function(resolve, reject){
					var imageOptions = {};
					imageOptions.centered = false;
					imageOptions.getImage = function(tagValue, tagName){
						return getBase64Image(imageURL, id); //converting image into bytes
					}
					imageOptions.getSize = function(img, tagValue, tagName){
						return [256, 256];
					}
					if(imageOptions.getImage && imageOptions.getSize){
						var imageModule = new ImageModule(imageOptions);
						resolve(imageModule);
					}else{
						reject("No Image Option")
					}
					
				});
				return promise;
                      }

and repeating this for number of images. After that I am attaching recieved image module to doc and setting data in doc.
doc.attachModule(imageModule)
doc.setData({"image1": "image1.png", "image2": "image2.png"})

but same image is loading everytime.

**Comment by edi9999** [comment]
What is the value of imageUrl ?

**Comment by edi9999** [comment]
Closing as stale
