### ISSUE TITLE
Issue while adding the Image to Doc

### ISSUE THREAD

**Issue by bhaskark08** [open-xml-templating/docxtemplater-image-module#87]
Hello , 

I am using this library in SAP UI5 Application and am able to download the word doc with data, but I am not able to add the images in the word document. (Loop and normal)
Could you please help me on this with some sample project. 

Below is the code which i am using to download the Doc file. 

	var opts = {}
		opts.centered = false;
		opts.getImage=function(tagValue, tagName) {
			  return fs.readFileSync(tagValue);
		}

		opts.getSize=function(img,tagValue, tagName) {
			return [150,150];
		}

var imageModule=new window.ImageModule(opts);

var zip = new JSZip(content);
var oDoc=new Docxtemplater()
.attachModule(imageModule)
.loadZip(zip) 
oDoc.setData(aData);		
						try{
							oDoc.render();
						}catch(e){
							console.log(e);
						}
						var sOutput = oDoc.getZip().generate({type:"blob"});
						jQuery.sap.require("sap.ui.core.util.File");
						sap.ui.core.util.File.save(sOutput, "Word", "docx");

Best Regards, 
Bhaskar.

**Comment by edi9999** [comment]
You have to replace the getImage part, as fs doesn't exist in the browser.

I will add an example in the doc on how to make it work in the browser. In the meantime have a look https://github.com/open-xml-templating/docxtemplater-image-module/issues/44

**Comment by bhaskark08** [comment]
Hi Edi9999 Thanks for the suggestion.  

Issue is resolved , i am doing with loading the images initially in base64 format and captured in array and am returning the same. 

So am able to display the images in Docx.

Will it be possible to create the Docx on basis of some conditions. 
Like if i have X for one field i need a row with 3 columns in Table else Row with 2 Columns.( Different data)  

Please suggest. 

Best Regards, 
Bhaskar.

**Comment by edi9999** [comment]
Yes you can do conditions.

See

http://docxtemplater.readthedocs.io/en/latest/tag_types.html#conditions

and

 http://docxtemplater.readthedocs.io/en/latest/angular_parse.html#conditions
