### ISSUE TITLE
Document header/footer image-tag replacement

### ISSUE THREAD

**Issue by bmatz** [open-xml-templating/docxtemplater-image-module#9]
I ran into the problem that the image-module threw the error 'cannot call method addImageRels of undefined' when i tried to use the image tag in docx documents footer/header.

I looked into this and it appears that a blank document with just a simple '{%image}' tag in header/footer doesn't create a corresponding '.xml.rels' file. Therefore the attempt to load a non existing header/footer.xml.rels is responsible for this error.

I already fixed this issue and will provide a pull request with 2 changes.
1. ImgManager.loadImageRels - Using the docx's file 'word/_rels/document.xml.rels' as fallback when the demanded file is not present.
2. ImageModule.replaceTag - don't try to call imgManagers addImageRels() if loadImageRels() returns nothing.

I also added an appropriate test. The other tests are not affected by this changes and still pass without any issues.

**Comment by edi9999** [comment]
Ok, great, solved with #10
