### ISSUE TITLE
failing to export images to word doc on chromium 58+

### ISSUE THREAD

**Issue by srikanthkatta2207** [open-xml-templating/docxtemplater-image-module#93]
we are trying to export images of type blob to word document using docx template image module, it was failing on latest versions of chromium(58), same images are exporting fine on chromium 55.

using these libraries in our project 
docxtemplater - 2.1.5
docxtemplate image module -1.0.4

**Comment by edi9999** [comment]
Can you try with latest version of both modules ?

**Comment by srikanthkatta2207** [comment]
Ok

**Comment by edi9999** [comment]
If the error still persists, it would be useful to have a stacktrace, or other detail about the error (template, data, code / URL to reproduce)

**Comment by sultanahamer** [comment]
Hi @edi9999 we have tested with latest versions and its working fine. We have a bug in our code giving image size always 0,0 and hence could not see image in exported word doc.

**Comment by edi9999** [comment]
Ok, good.
