### ISSUE TITLE
SVGs don't get rendered

### ISSUE THREAD

**Issue by BillBrower** [open-xml-templating/docxtemplater-image-module#97]
`gif`'s, `jpeg`'s, and `png`'s render correctly but when I try to render an `svg` I get a placeholder that says my computer doesn't have enough memory to load the image. Is there a way to render `svg`'s or are they unsupported?

**Comment by edi9999** [comment]
Indeed, svg's are not handled by word, you have to convert the image to another format before inserting it.

**Comment by BillBrower** [comment]
That's what I figured, thanks for confirming it!
