### ISSUE TITLE
Calling getRenderedPart outside the renderer

### ISSUE THREAD

**Issue by awerlang** [open-xml-templating/docxtemplater-image-module#98]
Hey!

We used the image module to produce a raw xml to be inserted with the raw xml module. It used to work on v1. Now, we're migrating to v3 and something substantial changed on the internals and this approach isn't working.

```js
// v1 client code
const imageModule: any = new ImageModule({centered: false});
doc.attachModule(imageModule);
imageModule.handleEvent('rendering-file', 'word/document.xml');

data.image = createImageXml(...);

doc.setData(data);
doc.render();
```

```js
// v1 
createImageXml(imgData) {
    // this: ImageModule
    const imageRels = this.loadImageRels();

    const imgBuffer = this.getImageFromData(imgData);
    const rId = imageRels.addImageRels(this.getNextImageName(), imgBuffer);
    const sizePixel = this.getSizeFromData(imgBuffer);
    const size = [this.convertPixelsToEmus(sizePixel[0]), this.convertPixelsToEmus(sizePixel[1])];

    if (this.options.centered) {
        return this.getImageXmlCentered(rId, size);
    } else {
        return this.getImageXml(rId, size);
    }
}
```

Below is the current code ported to v3. It fails because xmlDocuments isn't set on modules yet. A change on docxtemplater that makes a step forward (I guess) is add a call to `compile(true)` just before calling this piece of code, and also adding an early return on it to avoid running some parts twice:

```js
this.setModules({ zip: this.zip, xmlDocuments: this.xmlDocuments, data: this.data });
if (pre) return; // <<< pre is a parameter === true when called from client code
this.getTemplatedFiles();
```

With the early return (as above) it generates a blank docx file with the images added as resources. Without the early return it complains about a `<w:p>` not found.

```js
// v3
get imgManager() {
    const filePath = this.options.filePath || 'document.xml';
    let mgr = this.imgManagers[filePath];
    if (!mgr) {
        mgr = new ImgManager(this.zip, filePath, this.xmlDocuments, this.fileType);
        this.imgManagers[filePath] = mgr;
    }
    return mgr;
}

createImageXml(imgData) {
    const imgBuffer = this.getImageFromData(imgData);
    const rId = this.imgManager.addImageRels(this.getNextImageName(), imgBuffer);
    const sizePixel = this.getSizeFromData(imgBuffer);

    return this.getRenderedPart({}, rId, sizePixel).value;
}
```

I think the `compile()` method would need some tweaks to make the proper initialization. Also the `imgManager()` getter could be improved.

What do you advise here?

Thanks in advance!

**Comment by awerlang** [comment]
I've found a better way to deal with initialization of modules. By adding an extension point in `render()` we're able to call methods from modules in a valid state.

After compilation, the rendering process resumes once the promise resolves.

```js
/**
 * param cb (Function<Promise>) a function called after the compile step
 * returns Promise
 */
function render(cb) {
    var _this4 = this;

    this.compile();
    return Promise.resolve(cb && cb()).then(() => {
        this.mapper = this.modules.reduce(function (value, module) {
            return module.getRenderedMap(value);
        }, {});

        Object.keys(this.mapper).forEach(function (to) {
            var mapped = _this4.mapper[to];
            var from = mapped.from;
            var currentFile = _this4.compiled[from];
            currentFile.setTags(mapped.data);
            currentFile.render(to);
            _this4.zip.file(to, currentFile.content);
        });
        this.syncZip();
    });
}
```

```js
// client code
const imageModule: any = new ImageModule({centered: false});
doc.attachModule(imageModule);

doc.setData(data);
await doc.render(async () => {
    await ...
    data.image = createImageXml(...);
});

const buf = doc.getZip()
```

I'd prefer not having to change docxtemplater API, so I'd like to know what you think. If changing the API is the best way moving forward, then we could improve this design.

**Comment by awerlang** [comment]
Reviewing the code, there's already an extension point we can make use of, it's another module. Still, `getRenderedMap()` would return a promise instead.

**Comment by edi9999** [comment]
Sorry, but I'm not sure I understand what exactly is your underlying problem. Can you describe it before going into technical details ?

**Comment by awerlang** [comment]
Hey, I'm sorry if I put the cart before the horse. Our need is to insert images (a bunch of them), two of them per row and resizing as needed into a document, which we are generating with the raw module. We've tried the regular templating method but we've found it too limiting and we also encountered a few issues, the same ones other people already reported, like spacing and such. In order to do that, we need a way to generate the markup for the images and add them to the zip file. We found a way to achieve this on v1 (a hack ofc) and now we're migrating to v3.

I'm thinking now it doesn't have much to do with the image module, even though #90 is desired.

Let me know what you think.

Cheers

**Comment by awerlang** [comment]
Managed to solve the initial issue, by attaching a custom module:

```js
class CustomModule {
    constructor(private imageModule: ImageModule, private callback) {
    }

    getRenderedMap(value) {
        this.callback(this);
        return value;
    }
    ...
}
...
const imageModule = new ImageModule({
    centered: false,
    getImage: Function,
    getSize: Function,
});
doc.attachModule(imageModule);
doc.attachModule(new CustomModule(imageModule, (module) => beforeRender({ doc, imageModule: module }, service)));

doc.setData(data);
doc.render();
```

Obs: everything needs to be synchronous.
